DELETE  http://localhost:3001/api/persons/1
###
GET https://phonebook-backend-sigma.vercel.app/api/persons
###
GET http://localhost:3001/api/persons/12
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Manuel",
    "number":"298463982"
}