DELETE  https://phonebookbackend-production-e5a2.up.railway.app/api/persons/1
###
GET https://phonebookbackend-production-e5a2.up.railway.app/api/persons
###
GET https://phonebookbackend-production-e5a2.up.railway.app/api/persons/12
###
POST https://phonebookbackend-production-e5a2.up.railway.app/api/persons
Content-Type: application/json

{
    "name":"Manuel",
    "number":"298463982"
}
###
DELETE  http://localhost:3001/api/persons/63c22dbdf875fe3dcc873b1d
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/info
###
GET http://localhost:3001/api/persons/63c22dbdf875fe3dcc873b1d
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Manuel",
    "number":"298463982"
}
###
PUT  http://localhost:3001/api/persons/63c22edd62705c601b8deba0
Content-Type: application/json

{
    "number":"354sc1"
}